### ISSUE TITLE
Why does the gradience flatpak need `device=dri` GPU acceleration?

### ISSUE THREAD

**Issue by Apacelus** [flathub/com.github.GradienceTeam.Gradience#12]
Why does a "simple" (compared to say, a video editor) gui app need gpu acceleration?

Disabling that permission does not seem to slow down the app

**Comment by 0xMRTT** [comment]
From [Flatpak documentation](https://docs.flatpak.org/en/latest/sandbox-permissions.html?highlight=device%3Ddri#standard-permissions)

```
Standard permissions

The following permissions provide access to basic resources that applications commonly require, and can therefore be freely used:

...

--device=dri - OpenGL rendering
```

Maybe we can remove it if it's useless 

cc: @LyesSaadi, @daudix-UFO, @tfuxu

**Comment by daudix** [comment]
GTK4 have graphics acceleration, it is needed for smooth work (and yes, it's not useless)
