### ISSUE TITLE
Gnome Flatpak runtime no longer supported 

### ISSUE THREAD

**Issue by Scotty-Trees** [flathub/com.github.GradienceTeam.Gradience#17]
When running `flatpak update` I noticed a new warning as shown below: 

```
Looking for updates…

Info: runtime org.gnome.Platform branch 44 is end-of-life, with reason:
   The GNOME 44 runtime is no longer supported as of March 20, 2024. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
   com.github.GradienceTeam.Gradience, com.github.liferooter.textpieces, com.raggesilver.BlackBox, org.gnome.SoundRecorder, org.gnome.gitlab.somas.Apostrophe, org.gustavoperedo.FontDownloader

```

Please update the Gnome runtime to support the latest, thank you.

**Comment by superuser-miguel** [comment]
From the Gnome Software Center 

![2024-05-17_14-54-03](https://github.com/flathub/com.github.GradienceTeam.Gradience/assets/16271056/795b3470-2fa6-44a7-aeb7-d9f13980a48f)

**Comment by daudix** [comment]
App is no longer maintained and is indicated as EOL as of #20, so no longer relevant
